### ISSUE TITLE
Hello bro

### ISSUE THREAD

**Issue by iZotex** [LWSS/McDota#1]
How  use hack for windows? if switch libclient.so to client.dll? will be work or need to edit pattern & offsets?

**Comment by anarh1st47** [comment]
u need to edit offsets, patterns, maybe some interfaces due to second destructor on linux or valve specific

**Comment by iZotex** [comment]
Ok thanks, tell me what compiler to use under windows I think that in visual studio it will not be easy to build it

**Comment by anarh1st47** [comment]
In vs u can open cmakelists.txt(open*->cmake or smth like this) and it will load all files in directory. Disable compiler version checks firstly and it should start building, thats how i tried to fix skeletux on windows

**Comment by iZotex** [comment]
Thanks)))

**Comment by Un1xMida** [comment]
did u find a solution ?
