### ISSUE TITLE
help

### ISSUE THREAD

**Issue by noise14141** [LWSS/McDota#11]
in console
[McDota:VMTsHaveMisMatch] Camera VM count does not match; Is: (42), should be: (41)
[McDota:Main] One of the VMs has had a Mismatch. Stopping...

**Comment by noise14141** [comment]
fix
uint32_t cameraNum = 42; // been 41

**Comment by LWSS** [comment]
i'll look at it a bit later, but the entire vtable should be checked again. It's might be ok, but if they added something in the middle, everything will be shifted by 1

**Comment by noise14141** [comment]
P.S .Sorry for my bad eng , I will use a translator.

You did not think to make functions related to auto casts and finishing creeps?

**Comment by noise14141** [comment]
I used to write a cheat for cc go, but I gave up and after almost 2 years I want to take up Dota, is I ready to develop the project together?
