### ISSUE TITLE
Crashing when I start a match against bots

### ISSUE THREAD

**Issue by adingy2** [LWSS/McDota#18]
I injected with ./load-stealth but menu doesn't show up I tried ./load_carto, menu shows up but as soon as I start a match against bots the game crashes

**Comment by adingy2** [comment]
wayne@wayne:~/McDota$ ./load_carto
./load_carto: line 29: /proc/cartographer: Permission denied
./load_carto: line 30: /proc/cartographer: Permission denied
./load_carto: line 31: /proc/cartographer: Permission denied
Injecting Build ID: libMcDota.so
2
Successfully injected!

Is this normal? Sorry im a complete noob

**Comment by kolay-v** [comment]
I think you should run script as root `sudo ./load_carto`

**Comment by LWSS** [comment]
yeah u need to run loading as root due to ptrace permissions
