### ISSUE TITLE
New offsets

### ISSUE THREAD

**Issue by kolay-v** [LWSS/McDota#19]
After injecting, got this warning in Dota console and no menu. 
```[Console] Warning: Interface "Source2EngineToClient001"(libengine2.so) (0x7f48eded73a0) Has Changed. Expected it to have 173 VMs; has 174 VMs. Check for Broken offsets and Update interfaces.cpp```

**Comment by LWSS** [comment]
fixed this already, update

**Comment by kolay-v** [comment]
<3
