### ISSUE TITLE
UI does not open

### ISSUE THREAD

**Issue by Dragojlo** [LWSS/McDota#2]
Hey I've tried injecting McDota but the UI does not open upon pressing Insert Key. I tried a lot of different keys and combinations but nothing happens. Tried the 2 and 3 Injecting methods, both say ''Successfully injected!'' in the Terminal. 

This project seems very cool would really like to try it out! 
Thanks

**Comment by LWSS** [comment]
Does the console say anything?

I know the UI doesn't work on the pick screen

**Comment by Dragojlo** [comment]
Tried compiling it again and noticed the console says: 

> CMake Error at CMakeLists.txt:6 (message):
  Your GCC seems outdated.  ( Requires >=7.1 for C++17 support )


-- Configuring incomplete, errors occurred!
See also "/home/andrej/McDota-master/CMakeFiles/CMakeOutput.log".

However when trying to update to the newest compiler this came up:

> sudo apt-get install gcc-7 g++-7
Reading package lists... Done
Building dependency tree       
Reading state information... Done
g++-7 is already the newest version (7.3.0-27ubuntu1~18.04).
g++-7 set to manually installed.
gcc-7 is already the newest version (7.3.0-27ubuntu1~18.04).
gcc-7 set to manually installed.
The following packages were automatically installed and are no longer required:
  amd64-microcode dkms libvdpau1:i386 libxcb-xfixes0:i386
  mesa-vdpau-drivers:i386 thermald vdpau-driver-all:i386
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 40 not upgraded.

**Comment by LWSS** [comment]
weird, looks like cmake isn't picking up the ubuntu gcc version right.

you can comment these out https://github.com/LWSS/McDota/blob/master/CMakeLists.txt#L4-L10

**Comment by Dragojlo** [comment]
I just deleted that whole block you highlighted and after running ''cmake . && make -j'' I get this: https://pastebin.com/7z8tT5Si. Still not working. 

I'll try everything again on a different system later and let you know if it works. Are these the right commands to install the correct compiler? 

> sudo add-apt-repository ppa:jonathonf/gcc-7.1
sudo apt-get update
sudo apt-get install gcc-7 g++-7

Thanks for the help so far!

**Comment by LWSS** [comment]
yeah inline variables require C++17 which needs a newish compiler. 

I don't use ubuntu, but see if you can find a repo or something with a newer version. Clang is also an option

**Comment by Dragojlo** [comment]
OMG it works now. All I had to do was enable the console. Huuuge thanks for the help and for all your work creating this project! Keep it up

**Comment by LWSS** [comment]
Yeah it's a little buggy sometimes, but it's a new frontier.

There's really much for dota cheats that aren't just lua scripts.

**Comment by mdynnl** [comment]
```
Linux archlinux 5.3.1-arch1-1-ARCH #1 SMP PREEMPT Sat Sep 21 11:33:49 UTC 2019 x86_64 GNU/Linux
cmake version 3.15.3
gcc (GCC) 9.1.0
GNU gdb (GDB) 8.3
GNU Make 4.2.1
libprotoc 3.9.2
```
gets error saying `#error This file was generated by an older version of protoc` when compiling.
according to this SO https://stackoverflow.com/questions/53808555/protocol-buffer-error-due-to-incompatible-versions,
`rm src/protos/mcdota.pb.*`,
`protoc src/protos/mcdota.proto --cpp_out=.` and compiled successfully

used all three methods
UI does not open
In `/tmp/dotainterfaces.txt`,
```
-- Module Name: ... --
**Couldn't find CreateInterface**
```
and similar messages

may be they changed it??
