### ISSUE TITLE
Visuals broken

### ISSUE THREAD

**Issue by mrshroomy** [LWSS/McDota#26]
![image](https://user-images.githubusercontent.com/52048952/68315821-a9255500-00b8-11ea-829a-3a04cec02483.png)

**Comment by kolay-v** [comment]
Duplicate https://github.com/LWSS/McDota/issues/24

**Comment by LWSS** [comment]
again, I just turn on the game's built in debug rendering.

You need to fix your stretched resolution, low render resolution, or whatever to 100%
