### ISSUE TITLE
Pressing insert doesn't show anything

### ISSUE THREAD

**Issue by kranercc** [LWSS/McDota#27]
Dump:
krane@krop2:~/McDota$ ./load
Injecting Build ID: libMcDota.so
2
Successfully injected!
krane@krop2:~/McDota$ 

edit: ignore the lines above the text thing

**Comment by kolay-v** [comment]
Does it say anything in game console? It should write message about inject/error in game debug console

**Comment by kranercc** [comment]
checking it now

**Comment by kranercc** [comment]
[McDota] I'm in like Flynn.
[McDota] Your Dota 2 was Built on - Nov 06 2019 - 18:05:39PST
[McDota] ScreenSize: 2560x1080 - Max Clients: 1
[McDota] client @ 0x7f6c0bfc8e80 - [libclient.so]
[McDota] viewRender @ 0x7f6c0c09aa40 - [libclient.so]
[McDota] clientMode @ 0x7f6c0c002fc0 - [libclient.so]
[McDota] Camera @ 0x55a3dbac7580 - [Unknown]
[McDota] GameEventManger @ 0x7f6c0bfa81e0 - [libclient.so]
[McDota] SoundOpSystem @ 0x7f6c124fffc0 - [libsoundsystem.so]
[McDota] VScriptSystem @ 0x55a3d5cb53f0 - [Unknown]
[McDota] CFontManager @ 0x7f6c16462e40 - [libmaterialsystem2.so]
[McDota] CEngineServiceMgr @ 0x7f6c2a956d40 - [libengine2.so]
[McDota] RichPresence @ 0x7f6c0c035380 - [libclient.so]
[McDota] ParticleSystemMgr @ 0x7f6c11b4d400 - [libparticles.so]
[McDota] CNetworkMessages @ 0x7f6c13b46460 - [libnetworksystem.so]
[McDota] CGameEventSystem @ 0x7f6c2a9b1be0 - [libengine2.so]
[McDota] CVPhys2World @ 0x55a3d1d21200 - [Unknown]
[McDota] UI Engine @(0x55a3bf08c100) | Running? (yes)
[McDota] Active Loop Name: (game) | Addon String: ()
[McDota] NetworkGameClient @ 0x55a3dae17000 - [Unknown]
[McDota] GetAllClasses @ 0x55a3c7f94d80 - [Unknown]
[McDota] World2Screen @ 0x7f6c0bfe0800 - RenderGameSystem @ 0x55a3cf84a640
[McDota] Camera @ 0x55a3dbac7580
[McDota] Grabbing new NetworkGameClient VMT - 0x55a3dae17000
[McDota] Grabbing new NetChannel VMT - 0x55a3d21dc000




Now it works. So the fix for this problem would be to restart the pc aftter installing everytihng

**Comment by kolay-v** [comment]
You need inject it in game. And it will crash when game ends. So one game - 1 inject then crash

**Comment by kranercc** [comment]
Still the problem is not fixed

**Comment by LWSS** [comment]
should be ok
