### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by YEEEEEEE777** [LWSS/McDota#30]
![image](https://user-images.githubusercontent.com/33149580/71307622-c8c2d380-2401-11ea-9b2a-27b6d185579c.png)

**Comment by LWSS** [comment]
![adsf](https://i.imgur.com/FclxGRu.png)

note the last one

**Comment by YEEEEEEE777** [comment]
I tried to use this protobuf somehow but it didn’t work out
please give a little info about this lib
I have little knowledge about CMake and c

**Comment by LWSS** [comment]
install the development package

**Comment by YEEEEEEE777** [comment]
where to find? how to install?

**Comment by YEEEEEEE777** [comment]
![image](https://user-images.githubusercontent.com/33149580/71319372-81465100-24ae-11ea-83e5-fc11e4339007.png)

**Comment by kolay-v** [comment]
It is Linux only hack

**Comment by YEEEEEEE777** [comment]
lol I didn’t even know that DotA works on linux
