### ISSUE TITLE
Help me out "error This file was generated by an older version of protoc which is"

### ISSUE THREAD

**Issue by somenormalguy7** [LWSS/McDota#32]
Getting this error I Installed every thing properly. How to fix this?

`sham@sham:~/Downloads/McDota-master$ cmake . && make -j
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Protobuf: /usr/local/lib/libprotobuf.so;-lpthread (found version "3.11.2") 
-- Found Protobuf: /usr/local/lib/libprotobuf.so;-lpthread;-lpthread (found version "3.11.2") 
-- No build type selected, default to Release
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sham/Downloads/McDota-master
Scanning dependencies of target McDota
[  2%] Building CXX object CMakeFiles/McDota.dir/src/GUI/Gui.cpp.o
[  5%] Building CXX object CMakeFiles/McDota.dir/src/Hacks/Esp.cpp.o97%] Building CXX object CMakeFiles/McDota.dir/src/Hooks/SendNetMessage.cpp.o In file included from /home/sham/Downloads/McDota-master/src/protos/mcdota.pb.cpp:4:0: /home/sham/Downloads/McDota-master/src/protos/mcdota.pb.h:17:2: error: #error This file was generated by an older version of protoc which is #error This file was generated by an older version of protoc which is ^~~~~ /home/sham/Downloads/McDota-master/src/protos/mcdota.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please #error incompatible with your Protocol Buffer headers. Please ^~~~~ /home/sham/Downloads/McDota-master/src/protos/mcdota.pb.h:19:2: error: #error regenerate this file with a newer version of protoc. #error regenerate this file with a newer version of protoc. ^~~~~ In file included from /home/sham/Downloads/McDota-97%] Building CXX object CMakeFiles/McDota.dir/src/Hooks/SendNetMessage.cpp.o In file included from /home/sham/Downloads/McDota-master/src/protos/mcdota.pb.cpp:4:0: /home/sham/Downloads/McDota-master/src/protos/mcdota.pb.h:17:2: error: #error This file was generated by an older version of protoc which is #error This file was generated by an older version of protoc which is ^~~~~ /home/sham/Downloads/McDota-master/src/protos/mcdota.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please #error incompatible with your Protocol Buffer headers. Please ^~~~~ /home/sham/Downloads/McDota-master/src/protos/mcdota.pb.h:19:2: error: #error regenerate this file with a newer version of protoc. #error regenerate this file with a newer version of protoc. ^~~~~ In file included from /home/sham/Downloads/McDota-
[  7%] Building CXX object CMakeFiles/McDota.dir/src/Hacks/Zoom.cpp.o
[ 10%] Building CXX object CMakeFiles/McDota.dir/src/Hooks/FrameStageNotify.cpp.o
[ 13%] Building CXX object CMakeFiles/McDota.dir/src/Hooks/GetFogEnd.cpp.o
[ 15%] Building CXX object CMakeFiles/McDota.dir/src/Hooks/PostEventAbstract.cpp.o
[ 18%] Building CXX object CMakeFiles/McDota.dir/src/Utils/Math.cpp.o
[ 21%] Building CXX object CMakeFiles/McDota.dir/src/Hooks/RunScript.cpp.o
[ 23%] Building CXX object CMakeFiles/McDota.dir/src/Hooks/FireEventClientSide.cpp.o
[ 26%] Building CXX object CMakeFiles/McDota.dir/src/Netvars.cpp.o
[ 28%] Building CXX object CMakeFiles/McDota.dir/src/McDota.cpp.o
[ 31%] Building CXX object CMakeFiles/McDota.dir/src/Utils/Memory.cpp.o
[ 34%] Building CXX object CMakeFiles/McDota.dir/src/Utils/Protobuf.cpp.o
[ 36%] Building CXX object CMakeFiles/McDota.dir/src/Hooks/GetFoWAmount.cpp.o
[ 39%] Building CXX object CMakeFiles/McDota.dir/src/Utils/Integritycheck.cpp.o
[ 42%] Building CXX object CMakeFiles/McDota.dir/src/Utils/Util_sdk.cpp.o
[ 44%] Building CXX object CMakeFiles/McDota.dir/src/Hooks/CreateMove.cpp.o
[ 47%] Building CXX object CMakeFiles/McDota.dir/src/Hooks/SetKeyCodeState.cpp.o
[ 50%] Building CXX object CMakeFiles/McDota.dir/src/protos/mcdota.pb.cpp.o
[ 52%] Building CXX object CMakeFiles/McDota.dir/src/Hooks/GetZFar.cpp.o
[ 55%] Building CXX object CMakeFiles/McDota.dir/src/Hooks/PaintTraverse.cpp.o
[ 57%] Building CXX object CMakeFiles/McDota.dir/src/Hooks/StartSoundEvent.cpp.o
[ 60%] Building CXX object CMakeFiles/McDota.dir/src/Hooks/PostReceivedNetMessage.cpp.o
[ 63%] Building CXX object CMakeFiles/McDota.dir/src/Scanner.cpp.o
[ 65%] Building CXX object CMakeFiles/McDota.dir/src/Interfaces.cpp.o
[ 68%] Building CXX object CMakeFiles/McDota.dir/src/Hooks/Hard_BAsyncSendProto.cpp.o
[ 71%] Building CXX object CMakeFiles/McDota.dir/src/Utils/Util.cpp.o
[ 73%] Building CXX object CMakeFiles/McDota.dir/src/Utils/Draw.cpp.o
[ 76%] Building CXX object CMakeFiles/McDota.dir/src/Hooks/Hard_DispatchPacket.cpp.o
[ 78%] Building C object CMakeFiles/McDota.dir/src/Utils/subhook/subhook.c.o
[ 81%] Building CXX object CMakeFiles/McDota.dir/src/Settings.cpp.o
[ 84%] Building CXX object CMakeFiles/McDota.dir/src/Hooks/LevelInit.cpp.o
[ 86%] Building CXX object CMakeFiles/McDota.dir/src/Hooks/CreateNetChannel.cpp.o
[ 89%] Building CXX object CMakeFiles/McDota.dir/src/Hooks/DeleteParticleCollection.cpp.o
[ 92%] Building CXX object CMakeFiles/McDota.dir/src/Utils/Patternfinder.cpp.o
[ 94%] Building CXX object CMakeFiles/McDota.dir/src/Hooks/CreateParticleCollection.cpp.o
[ 97%] Building CXX object CMakeFiles/McDota.dir/src/Hooks/SendNetMessage.cpp.o
In file included from /home/sham/Downloads/McDota-master/src/protos/mcdota.pb.cpp:4:0:
/home/sham/Downloads/McDota-master/src/protos/mcdota.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^~~~~
/home/sham/Downloads/McDota-master/src/protos/mcdota.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^~~~~
/home/sham/Downloads/McDota-master/src/protos/mcdota.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
  ^~~~~
In file included from /home/sham/Downloads/McDota-master/src/Hooks/CreateMove.cpp:6:0:
/home/sham/Downloads/McDota-master/src/Hooks/../protos/mcdota.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is`97%] Building CXX object CMakeFiles/McDota.dir/src/Hooks/SendNetMessage.cpp.o In file included from /home/sham/Downloads/McDota-master/src/protos/mcdota.pb.cpp:4:0: /home/sham/Downloads/McDota-master/src/protos/mcdota.pb.h:17:2: error: #error This file was generated by an older version of protoc which is #error This file was generated by an older version of protoc which is ^~~~~ /home/sham/Downloads/McDota-master/src/protos/mcdota.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please #error incompatible with your Protocol Buffer headers. Please ^~~~~ /home/sham/Downloads/McDota-master/src/protos/mcdota.pb.h:19:2: error: #error regenerate this file with a newer version of protoc. #error regenerate this file with a newer version of protoc. ^~~~~ In file included from /home/sham/Downloads/McDota-

[error.txt](https://github.com/LWSS/McDota/files/4113456/error.txt)

**Comment by LWSS** [comment]
`#error regenerate this file with a newer version of protoc.`

regenerate mcdota.proto and make sure to rename it from .cc->.cpp

**Comment by LWSS** [comment]
i think I need to push update too btw

**Comment by somenormalguy7** [comment]
> `#error regenerate this file with a newer version of protoc.`
> 
> regenerate mcdota.proto and make sure to rename it from .cc->.cpp

Could you guide me which in which directory I can find mcdota.proto and how to regenerate and rename because i'm completely new for Linux .

Thank you

**Comment by LWSS** [comment]
```
cd src/protos
protoc --cpp_out=$(pwd) mcdota.proto 
mv mcdota.pb.cc mcdota.pb.cpp
```

**Comment by somenormalguy7** [comment]
sham@sham:~/Downloads/McDota-master/src/protos$ protoc --cpp_out=$(pwd) mcdota.proto

[libprotobuf WARNING google/protobuf/compiler/parser.cc:646] No syntax specified for the proto file: mcdota.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)

sham@sham:~/Downloads/McDota-master/src/protos$

**Comment by LWSS** [comment]
just a warning

**Comment by somenormalguy7** [comment]
Thank you it's done 
Now I have to figure out how to use it.
