### ISSUE TITLE
Sucesfully injected but not

### ISSUE THREAD

**Issue by kranercc** [LWSS/McDota#40]
krane@krane:~/McDota$ ./load-stealth 
./load-stealth: line 36: victim_lib_array: bad array subscript
./load-stealth: line 47: victim_lib_array[-1]: bad array subscript
cp: cannot create regular file '': No such file or directory
patchelf: getting info about '': No such file or directory
McDota > Attaching McDota spoofed as  to PID dota
McDota > McDota has been successfully injected.

Dota2 console is clean and no keybind works [ins home etc]

Edit1: ./load works ./load-stealth doesn't

**Comment by LWSS** [comment]
yeah load-stealth stinks, i should just remove it
