### ISSUE TITLE
Guide for Lua scripts

### ISSUE THREAD

**Issue by llzewy** [LWSS/McDota#44]
Hello !  I did not quite understand how to make the luna script work, I'm sorry.  I have a lot of .lua files, but I don’t know what to do with them to make it work in the game, please help me, thanks !!!!

**Comment by LWSS** [comment]
https://github.com/LWSS/McDota/issues/41

**Comment by llzewy** [comment]
Yes, thank you, I already read this, before ask you, maybe it’s really hard for me.. I put .lua script in this directory, and open cheat, but anything don’t change, I don’t understand what is “bazinga”, maybe you have link to can help me thank you ?
