### ISSUE TITLE
Issues with getting handle to vgui2.dll

### ISSUE THREAD

**Issue by darksoul577** [LWSS/McDota#47]
In Windows, vgui2.dll is not showing up as being loaded by dota2.exe.Do you have that same issue in Linux? It seems that Dota2 may be removing it from the Process Environment Block, so that we are unable to get the handle for loading that module.

**Comment by LWSS** [comment]
nope
```
[lwss@localhost ~]$ cat /proc/$(pidof dota2)/maps | grep vgui
7ff898b20000-7ff898b60000 r-xp 00000000 fd:02 16646605                   /home/lwss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libvgui2.so
7ff898b60000-7ff898d60000 ---p 00040000 fd:02 16646605                   /home/lwss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libvgui2.so
7ff898d60000-7ff898d63000 r--p 00040000 fd:02 16646605                   /home/lwss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libvgui2.so
7ff898d63000-7ff898d65000 rw-p 00043000 fd:02 16646605                   /home/lwss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libvgui2.so
7ff898d68000-7ff898f41000 r-xp 00000000 fd:02 16646606                   /home/lwss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libvguirendersurface.so
7ff898f41000-7ff899141000 ---p 001d9000 fd:02 16646606                   /home/lwss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libvguirendersurface.so
7ff899141000-7ff8991a7000 r--p 001d9000 fd:02 16646606                   /home/lwss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libvguirendersurface.so
7ff8991a7000-7ff8991a8000 rw-p 0023f000 fd:02 16646606                   /home/lwss/.local/share/Steam/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libvguirendersurface.so
[lwss@localhost ~]$
```

**Comment by darksoul577** [comment]
Appreciate the fast response, and thanks for updating the sdk files. It's been really helpful for me.

**Comment by LWSS** [comment]
np brother

**Comment by kazooline** [comment]
> In Windows, vgui2.dll is not showing up as being loaded by dota2.exe.Do you have that same issue in Linux? It seems that Dota2 may be removing it from the Process Environment Block, so that we are unable to get the handle for loading that module.

Did you find the solution? Got the same problem. vgui2.dll not getting loaded. No other loaded DLL got the string "VGUI_Panel".
Can't find anything on the web about the problem besides your issue here. Hope to hear from you...

**Comment by darksoul577** [comment]
> > In Windows, vgui2.dll is not showing up as being loaded by dota2.exe.Do you have that same issue in Linux? It seems that Dota2 may be removing it from the Process Environment Block, so that we are unable to get the handle for loading that module.
> 
> Did you find the solution? Got the same problem. vgui2.dll not getting loaded. No other loaded DLL got the string "VGUI_Panel".
> Can't find anything on the web about the problem besides your issue here. Hope to hear from you...

Yeah, make sure you have -console in the command line arguments. Vgui2.dll only loads if the debugging console is enabled.

**Comment by kazooline** [comment]
> > > In Windows, vgui2.dll is not showing up as being loaded by dota2.exe.Do you have that same issue in Linux? It seems that Dota2 may be removing it from the Process Environment Block, so that we are unable to get the handle for loading that module.
> > 
> > 
> > Did you find the solution? Got the same problem. vgui2.dll not getting loaded. No other loaded DLL got the string "VGUI_Panel".
> > Can't find anything on the web about the problem besides your issue here. Hope to hear from you...
> 
> Yeah, make sure you have -console in the dota command line arguments (i.e., create a shortcut "C:\Program Files (x86)\Steam\steamapps\common\dota 2 beta\game\bin\win64\dota2.exe" -console). Vgui2.dll only loads if the debugging console is enabled.

I already tried that. Still not loaded. I renamed vgui2.dll, and still game starts up without problem. When did you test your hooks the last time? Maybe a while ago? Maybe it changed/updated?

**Comment by darksoul577** [comment]
> > > > In Windows, vgui2.dll is not showing up as being loaded by dota2.exe.Do you have that same issue in Linux? It seems that Dota2 may be removing it from the Process Environment Block, so that we are unable to get the handle for loading that module.
> > > 
> > > 
> > > Did you find the solution? Got the same problem. vgui2.dll not getting loaded. No other loaded DLL got the string "VGUI_Panel".
> > > Can't find anything on the web about the problem besides your issue here. Hope to hear from you...
> > 
> > 
> > Yeah, make sure you have -console in the dota command line arguments (i.e., create a shortcut "C:\Program Files (x86)\Steam\steamapps\common\dota 2 beta\game\bin\win64\dota2.exe" -console). Vgui2.dll only loads if the debugging console is enabled.
> 
> I already tried that. Still not loaded. I renamed vgui2.dll, and still game starts up without problem. When did you test your hooks the last time? Maybe a while ago? Maybe it changed/updated?

It's been about a year since I used vgui. I wasn't a fan of its painttraverse techniques so I replaced that with  a directx hook. There's tutorials for how to hook directx on guidedhacking.

**Comment by kazooline** [comment]
> > > > > In Windows, vgui2.dll is not showing up as being loaded by dota2.exe.Do you have that same issue in Linux? It seems that Dota2 may be removing it from the Process Environment Block, so that we are unable to get the handle for loading that module.
> > > > 
> > > > 
> > > > Did you find the solution? Got the same problem. vgui2.dll not getting loaded. No other loaded DLL got the string "VGUI_Panel".
> > > > Can't find anything on the web about the problem besides your issue here. Hope to hear from you...
> > > 
> > > 
> > > Yeah, make sure you have -console in the dota command line arguments (i.e., create a shortcut "C:\Program Files (x86)\Steam\steamapps\common\dota 2 beta\game\bin\win64\dota2.exe" -console). Vgui2.dll only loads if the debugging console is enabled.
> > 
> > 
> > I already tried that. Still not loaded. I renamed vgui2.dll, and still game starts up without problem. When did you test your hooks the last time? Maybe a while ago? Maybe it changed/updated?
> 
> It's been about a year since I used vgui. I wasn't a fan of its painttraverse techniques so I replaced that with a directx hook. There's tutorials for how to hook directx on guidedhacking.

Yes, I know. Done that already in other games. Thanks anyways!
