### ISSUE TITLE
Render all particles

### ISSUE THREAD

**Issue by darksoul577** [LWSS/McDota#52]
hey LWSS -- I ported your code to Windows and added the all particle rendering feature (maphack).

https://github.com/darksoul577/ReShade

Basically, you just hook or call the SetRenderingEnabled function and set it to true. The function is easy to find because its the function in CParticleCollection with these strings "#STR: "Error in child list of particle system %s [%p], parent: %p, "m_Children.m_pHead: [%p]\n", "Address of m_Children.m_pHead: [%p]\n", "Offset of m_Children.m_pHead: [%i]\n", "Memory at [%p]:\n", "\n %4i:", "%02x", "Child collection: [%p]", "next: %p, parent: %p\n""

**Comment by LWSS** [comment]
Yeah not a bad idea, I think hooking GetRenderingEnabled() and just returning true would work too. There's probably another way in the fog system somewhere since there's a convar for it.
