### ISSUE TITLE
How can I run Panorama JS API?

### ISSUE THREAD

**Issue by snajdovski** [LWSS/McDota#53]
What syntax should I use to run JS scripts? I have Kubuntu LTS installed

**Comment by LWSS** [comment]
Here's an example: https://github.com/LWSS/McDota/blob/master/src/GUI/Gui.cpp#L140-L142

Keep in mind that each xml file has it's own js scope, don't think I figured out the int params, they are normally 8/10 when used by the game.

**Comment by snajdovski** [comment]
> Here's an example: https://github.com/LWSS/McDota/blob/master/src/GUI/Gui.cpp#L140-L142
> 
> Keep in mind that each xml file has it's own js scope, don't think I figured out the int params, they are normally 8/10 when used by the game.

Thanks I made it work.

**Comment by LWSS** [comment]
np
