### ISSUE TITLE
Problem with the libvgui2.so library

### ISSUE THREAD

**Issue by msph17** [LWSS/McDota#57]
The libvgui2.so library is not loaded, I checked with the command "cat / proc / $ (pidof dota2) / maps".

https://pastebin.com/raw/PQ8q7xAu

Dota console.

[Console] GetInterface: Could not open library: ./libvgui2.so
[Console] GetInterface: Could not open library: ./libvgui2.so
[Console] Interface: (VGUI_InputInternal001) is Null!
[Console] Interface: (VGUI_Panel010) is Null!
[Console] [McDota] FindExportedInterfaces () Failed. Stopping ...

I use pop_os!
kernel 5.8.0-7630-generic
protobuf-3.8.0.cpp

Do you have any idea what I can do?

**Comment by LWSS** [comment]
-vguiconsole for now

**Comment by msph17** [comment]
Worked perfectly.
Thanks.
