### ISSUE TITLE
Animation start/end hooks

### ISSUE THREAD

**Issue by ShadowFiendzxc** [LWSS/McDota#58]
Do you know any function that can be used for hooks:
OnUnitAnimationStart (C_BaseEntity *, animation_name)
and
OnUnitAnimationEnd (C_BaseEntity *)?

I spent a lot of time searching but couldn't find anything better than C_TEUnitAnimation :: RunUnitAnimation
but the problem is that it doesn't work for some abilities. (sf razes, axe call )

**Comment by LWSS** [comment]
the animations are actually a packet sent from the server->client.

```
animation start
message CDOTAUserMsg_TE_UnitAnimation {
	optional int32 entity = 1;
	optional int32 sequenceVariant = 2;
	optional float playbackrate = 3;
	optional float castpoint = 4;
	optional int32 type = 5;
	optional int32 activity = 6;
}

animation cancel
message CDOTAUserMsg_TE_UnitAnimationEnd {
	optional int32 entity = 1;
	optional bool snap = 2;
}
```
easiest to intercept it here
