### ISSUE TITLE
Stupid Questions:how do u get these SDK information

### ISSUE THREAD

**Issue by InnovationLou** [LWSS/McDota#59]
I'm new to Game Reverse and interested in Dota2 recently,could u plz tell me where or how to find these sdk info.I'd appreciate if u can give some help.

**Comment by LWSS** [comment]
basically they release debug versions of the linux/mac versions by accident once in a while, that's where all the function names come from.

Last time was in 2017 or so

manifests
3040374730712014712
2821943592690435352

**Comment by InnovationLou** [comment]
Thx u can close issue now and I may try windows version later

**Comment by LWSS** [comment]
ok, note that the windows version will only have 1 virtual destructor per class
