### ISSUE TITLE
zconf.h // readlink

### ISSUE THREAD

**Issue by ddjem87** [LWSS/McDota#6]
zconf.h // readlink
error and i dont know what to do with it
there is no zconf.h in the McDota folder so?
any help?

**Comment by ddjem87** [comment]
i removed zconf.h from the code and its compiling now but it does not open the menu any help?

**Comment by LWSS** [comment]
I think zlib-dev is the package you're looking for

**Comment by ddjem87** [comment]
now its seems to compile but its not opening the menu

OS: KDE Neon
Kernel: 5.0.14

**Comment by LWSS** [comment]
does it say anything in the console?

**Comment by ddjem87** [comment]
nothing else then injected

**Comment by LWSS** [comment]
try setting this

https://github.com/LWSS/McDota/blob/master/CMakeLists.txt#L33

**Comment by ddjem87** [comment]
i am sorry i do not understand what you mean by setting it i am not good with c++ if you mean to do something in the code :D

**Comment by LWSS** [comment]
`-static-libstdc++` add to linker flags and run cmake again

also can i see the output of `ldd -r libmcdota.so`

**Comment by ddjem87** [comment]
it did not work again this is what i made sorry if i am a monkey

first:
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS -static-libstdc++} ")# -static-libstdc++")

second:
set(CMAKE_SHARED_LINKER_FLAGS "${-static-libstdc++} ")# -static-libstdc++")

**Comment by LWSS** [comment]
`set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -static-libstdc++")`

like this

**Comment by ddjem87** [comment]
still doesn't work
