### ISSUE TITLE
Is this still working in patch 7.30d?

### ISSUE THREAD

**Issue by aeristhy** [LWSS/McDota#63]

**Comment by LWSS** [comment]
bout halfway done fixing it, changed quite a bit, but I've seen worse

**Comment by aeristhy** [comment]
Great, thank you for the response. I'll be watching this repo, thank you

**Comment by aeristhy** [comment]
@LWSS I just noticed, this build/hack is for Linux? Don't we have or can't we use this for windows?

**Comment by LWSS** [comment]
> @LWSS I just noticed, this build/hack is for Linux? Don't we have or can't we use this for windows?

yeah linux-only. I'm done fixing it for the most part but they removed some of the methods I used to load my UI layout. Will have to come up with another way...

**Comment by aeristhy** [comment]
> > @LWSS I just noticed, this build/hack is for Linux? Don't we have or can't we use this for windows?
> 
> yeah linux-only. I'm done fixing it for the most part but they removed some of the methods I used to load my UI layout. Will have to come up with another way...
> 
> Luckily the settings are all via convar so I can just flick them on/off, let me know if u guys actually use the cheat and want a non-UI version

Kinda unfortunate, I only play in Windows. Would be nice if we can have a windows version for this.

**Comment by ShahriyarB** [comment]
I appreciate your work
What has changed for 7.30d that broke in game ui system or other features of mcdota ?
Did class vtables get heavily changed or something ?

**Comment by LWSS** [comment]
ok I finally pushed, I normally tinker w/ this on weekends now, forget some times

**Comment by aeristhy** [comment]
Make a windows version of this XD

**Comment by LWSS** [comment]
> Make a windows version of this XD

mmmmmmmmmmmmmmmmmmmmmno

**Comment by aeristhy** [comment]
aw :(
