### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ghost** [LWSS/McDota#69]
I injected in game via stealth method but UI not showing up, restarting steam and game but not works then and restarting system again not working
this is my terminal
```
/McDota$ sudo ./load-stealth
./load-stealth: line 36: victim_lib_array: bad array subscript
./load-stealth: line 47: victim_lib_array[-1]: bad array subscript
cp: cannot create regular file '': No such file or directory
sudo: patchelf: command not found
McDota > Attaching McDota spoofed as  to PID dota
McDota > McDota has been successfully injected.

```
it said successfully injected but in game console nothing shows and `Insert` not works

**Comment by LWSS** [comment]
yeah dota sucks, you should just quit

**Comment by ghost** [comment]
is there any way to unlock sv_cheats?
there are some sources but they are built for windows, do you have any suggestion?

**Comment by rikudouIO** [comment]
> 

Use SDK or patch libengine.so

**Comment by ghost** [comment]
thank you
