### ISSUE TITLE
guide to install 

### ISSUE THREAD

**Issue by arwinder-sesto** [LWSS/McDota#7]
Hi I tried ```cmake . && make -j``` but i keep getting gcc outdate error. my version is gcc 7.4.

**Comment by arwinder-sesto** [comment]
[CMakeOutput.log](https://github.com/LWSS/McDota/files/3224206/CMakeOutput.log)

This is my log

**Comment by LWSS** [comment]
```gcc version 5.5.0 20171010 (Ubuntu 5.5.0-12ubuntu1~16.04) ```
sounds like you have multiple gcc's installed. Lookup how to select gcc version ( something like update-alternatives ) on ubuntu or remove the old version.
