### ISSUE TITLE
SendNetMessage hook crash

### ISSUE THREAD

**Issue by ChingChongWong** [LWSS/McDota#8]
Some features from the hook cause crashes: tested with send status, cmd repeater
I toggle them, tweak the slider a bit and and my game crashes

Can you also tell me, what does command_repeater do?

**Comment by ChingChongWong** [comment]
Toggle cmd repeater, set any random power value, click anywhere -> instant crash

**Comment by LWSS** [comment]
these are experimental features and those aren't crashes, it's just the game crashes when the server disconnects you in a sloppy way
